build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
args:
  APP_REPO: "https://github.com/stuartparmenter/media-proxy"
  APP_REF: "v0.5.9"