name: Media Proxy
version: "0.4.4"
slug: media_proxy
description: "WebSocket-controlled media proxy that outputs DDP (UDP)"
url: https://github.com/stuartparmenter/media-proxy
arch: [aarch64, amd64]
image: "ghcr.io/stuartparmenter/{arch}-media-proxy-addon"
startup: services
init: false
host_network: true          # DDP over UDP to arbitrary targets = easiest with host net
panel_icon: mdi:video-wireless
map: [addon_config, media]
environment: { PYTHONUNBUFFERED: "1" }
ports:
  8788/tcp: 8788            # WebSocket control (/control)
ports_description:
  8788/tcp: WebSocket control (/control)
options:
  host: "0.0.0.0"
  port: 8788
  log_level: "INFO"
schema:
  host: str
  port: int
  log_level: "list(DEBUG|INFO|WARNING|ERROR)"
devices:
  - /dev/dri
tmpfs: true  # Enable tmpfs for /tmp - faster image caching using RAM
